# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.NullBooleanField(default=None, verbose_name='Your_vote'),
        ),
    ]
